name: flutter_network_capabilities
description: This package allows monitoring of Network Capabilities from Android and iOS devices.
version: 0.0.1
homepage: https://nubank.com/ 
repository: https://github.com/nubank/flutter-network-capabilities

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nu.flutter_network_capabilities
        pluginClass: FlutterNetworkCapabilitiesPlugin
      ios:
        pluginClass: FlutterNetworkCapabilitiesPlugin
